-- Create users table
CREATE TABLE IF NOT EXISTS users (
    id            VARCHAR(36) PRIMARY KEY NOT NULL, -- UUID
    username      VARCHAR(50) UNIQUE NOT NULL,
    email         VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name          VARCHAR(100) NOT NULL,
    role          ENUM('user', 'admin') NOT NULL DEFAULT 'user',
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_is_active ON users(is_active);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at);

-- Seed initial admin user
-- IMPORTANT: The password_hash here is a placeholder and MUST be replaced
-- with a securely hashed password before running in a real environment.
-- For local development, one might use a known hashed password.
-- Example bcrypt hash for 'adminpassword': b2
-- Replace this with an actual hash generated by your chosen hashing algorithm (e.g., bcrypt)
-- For this MVP, we'll add a placeholder that the developer must replace.
-- A better seeding strategy might involve a separate seeding script
-- or a mechanism to prompt for admin credentials during initial setup.

-- Placeholder for admin user - developer needs to insert a valid hashed password
INSERT INTO users (id, username, email, password_hash, name, role, is_active)
VALUES (
    '00000000-0000-0000-0000-000000000admin', -- Static placeholder UUID for admin
    'admin',
    'admin@example.com',
    'placeholder_bcrypt_hash_for_adminpassword', -- REPLACE THIS!
    'Administrator',
    'admin',
    TRUE
) ON DUPLICATE KEY UPDATE username = 'admin'; -- Avoid error if run multiple times, though IDs should be unique
